[package]
name = "rust_embedded"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
microbit-v2 = "0.15"
cortex-m-rt = "0.7"
panic-halt = "0.2"
rtt-target = "0.5"
lsm303agr = "1"
