[package]
name = "rust_embedded"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-halt = "0.2"
rtt-target = "0.5"
stm32f4xx-hal = { version = "0.21", features = ["stm32f407"] }
